// TODO: Read from env
export const jwtConstants = {
  secret:
    'THATS JUST FOR TESTING OK! DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};
